// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe        = require("reason-react/src/reactDOMRe.js");
var ReasonReact       = require("reason-react/src/reasonReact.js");
var Page$BsMaterialUi = require("./page.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Page$BsMaterialUi.make("bs-material-ui", /* array */[])), "index");

/*  Not a pure module */
