// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact  = require("reason-react/src/reasonReact.js");
var MaterialUi   = require("material-ui");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(alt, className, classes, childrenClassName, component, imgProps, sizes, src, srcSet, style, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.Avatar, {
              alt: Js_undefined.from_opt(alt),
              childrenClassName: Js_undefined.from_opt(childrenClassName),
              className: Js_undefined.from_opt(className),
              classes: Js_undefined.from_opt(classes),
              component: Js_undefined.from_opt(component),
              imgProps: Js_undefined.from_opt(imgProps),
              sizes: Js_undefined.from_opt(sizes),
              src: Js_undefined.from_opt(src),
              srcSet: Js_undefined.from_opt(srcSet),
              style: Js_undefined.from_opt(style)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
