// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact        = require("reason-react/src/reasonReact.js");
var MaterialUi         = require("material-ui");
var Js_undefined       = require("bs-platform/lib/js/js_undefined.js");
var Utils$BsMaterialUi = require("./utils.js");

function make(style, onClick, component, className, centerRipple, disableRipple, focusRipple, disabled, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.ButtonBase, {
              focusRipple: Utils$BsMaterialUi.unwrapBool(focusRipple),
              centerRipple: Utils$BsMaterialUi.unwrapBool(centerRipple),
              disableRipple: Utils$BsMaterialUi.unwrapBool(disableRipple),
              disabled: Utils$BsMaterialUi.unwrapBool(disabled),
              onClick: Js_undefined.from_opt(onClick),
              component: Js_undefined.from_opt(component),
              className: Js_undefined.from_opt(className),
              style: Js_undefined.from_opt(style)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
