// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact        = require("reason-react/src/reasonReact.js");
var MaterialUi         = require("material-ui");
var Js_undefined       = require("bs-platform/lib/js/js_undefined.js");
var Utils$BsMaterialUi = require("./utils.js");

function make(raised, onClick, dense, disableFocusRipple, disableRipple, disabled, fab, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.Button, {
              raised: Utils$BsMaterialUi.unwrapBool(raised),
              dense: Utils$BsMaterialUi.unwrapBool(dense),
              disableFocusRipple: Utils$BsMaterialUi.unwrapBool(disableFocusRipple),
              disableRipple: Utils$BsMaterialUi.unwrapBool(disableRipple),
              disabled: Utils$BsMaterialUi.unwrapBool(disabled),
              fab: Utils$BsMaterialUi.unwrapBool(fab),
              onClick: Js_undefined.from_opt(onClick)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
