// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact  = require("reason-react/src/reasonReact.js");
var MaterialUi   = require("material-ui");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(style, avatar, subheader, title, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.cardHeader, {
              style: Js_undefined.from_opt(style),
              avatar: Js_undefined.from_opt(avatar),
              subheader: Js_undefined.from_opt(subheader),
              title: Js_undefined.from_opt(title)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
