// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact        = require("reason-react/src/reasonReact.js");
var MaterialUi         = require("material-ui");
var Js_undefined       = require("bs-platform/lib/js/js_undefined.js");
var Utils$BsMaterialUi = require("./utils.js");

function make(disableActionSpacing, style, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.CardActions, {
              disableActionSpacing: Utils$BsMaterialUi.unwrapBool(disableActionSpacing),
              style: Js_undefined.from_opt(style)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
