// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact                               = require("reason-react/src/reasonReact.js");
var Js_undefined                              = require("bs-platform/lib/js/js_undefined.js");
var Utils$BsMaterialUi                        = require("./utils.js");
var MaterialUi$slashtransitions$slashCollapse = require("material-ui/transitions/Collapse");

function make(expanded, transitionDuration, children) {
  return ReasonReact.wrapJsForReason(MaterialUi$slashtransitions$slashCollapse.collapse, {
              in: Utils$BsMaterialUi.unwrapBool(expanded),
              transitionDuration: Js_undefined.from_opt(transitionDuration)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
