// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var Js_boolean   = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact  = require("reason-react/src/reasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Collapse     = require("material-ui/transitions/Collapse");

function make(expanded, transitionDuration, children) {
  return ReasonReact.wrapJsForReason(Collapse, {
              in: Js_boolean.to_js_boolean(expanded),
              transitionDuration: Js_undefined.from_opt(transitionDuration)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
