// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact  = require("reason-react/src/reasonReact.js");
var MaterialUi   = require("material-ui");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(classes, enterTransitionDuration, leaveTransitionDuration, fullScreen, ignoreBackdropClick, ignoreEscapeKeyUp, style, onBackdropClick, onEnter, onEntered, onEntering, onEscapeKeyUp, onExit, onExited, onExiting, onRequestClose, openDialog, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.Dialog, {
              style: Js_undefined.from_opt(style),
              classes: Js_undefined.from_opt(classes),
              fullScreen: Js_undefined.from_opt(fullScreen),
              leaveTransitionDuration: Js_undefined.from_opt(leaveTransitionDuration),
              enterTransitionDuration: Js_undefined.from_opt(enterTransitionDuration),
              ignoreEscapeKeyUp: Js_undefined.from_opt(ignoreEscapeKeyUp),
              ignoreBackdropClick: Js_undefined.from_opt(ignoreBackdropClick),
              onBackdropClick: Js_undefined.from_opt(onBackdropClick),
              onEnter: Js_undefined.from_opt(onEnter),
              onEntered: Js_undefined.from_opt(onEntered),
              onEntering: Js_undefined.from_opt(onEntering),
              onEscapeKeyUp: Js_undefined.from_opt(onEscapeKeyUp),
              onExit: Js_undefined.from_opt(onExit),
              onExited: Js_undefined.from_opt(onExited),
              onExiting: Js_undefined.from_opt(onExiting),
              onRequestClose: Js_undefined.from_opt(onRequestClose),
              open: Js_undefined.from_opt(openDialog)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
