// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact          = require("reason-react/src/reasonReact.js");
var Js_undefined         = require("bs-platform/lib/js/js_undefined.js");
var MaterialUi$slashForm = require("material-ui/Form");
var Utils$BsMaterialUi   = require("./utils.js");

function make(disabled, checked, control, label, name, onChange, value, className, style, children) {
  return ReasonReact.wrapJsForReason(MaterialUi$slashForm.FormControlLabel, {
              checked: Js_undefined.from_opt(checked),
              label: Js_undefined.from_opt(label),
              control: Js_undefined.from_opt(control),
              disabled: Utils$BsMaterialUi.unwrapBool(disabled),
              name: Js_undefined.from_opt(name),
              onChange: Js_undefined.from_opt(onChange),
              value: Js_undefined.from_opt(value),
              style: Js_undefined.from_opt(style),
              className: Js_undefined.from_opt(className)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
