// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact          = require("reason-react/src/reasonReact.js");
var Js_undefined         = require("bs-platform/lib/js/js_undefined.js");
var MaterialUi$slashForm = require("material-ui/Form");
var Utils$BsMaterialUi   = require("./utils.js");

function make(disabled, error, fullWidth, required, margin, className, style, children) {
  return ReasonReact.wrapJsForReason(MaterialUi$slashForm.FormControl, {
              disabled: Utils$BsMaterialUi.unwrapBool(disabled),
              error: Utils$BsMaterialUi.unwrapBool(error),
              fullWidth: Utils$BsMaterialUi.unwrapBool(fullWidth),
              required: Utils$BsMaterialUi.unwrapBool(required),
              margin: Js_undefined.from_opt(margin),
              className: Js_undefined.from_opt(className),
              style: Js_undefined.from_opt(style)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
