// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact        = require("reason-react/src/reasonReact.js");
var MaterialUi         = require("material-ui");
var Js_undefined       = require("bs-platform/lib/js/js_undefined.js");
var Utils$BsMaterialUi = require("./utils.js");

function make(align, component, direction, wrap, justify, xl, lg, md, sm, xs, spacing, container, item, className, style, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.Grid, {
              container: Utils$BsMaterialUi.unwrapBool(container),
              item: Utils$BsMaterialUi.unwrapBool(item),
              style: Js_undefined.from_opt(style),
              className: Js_undefined.from_opt(className),
              align: Js_undefined.from_opt(align),
              component: Js_undefined.from_opt(component),
              direction: Js_undefined.from_opt(direction),
              wrap: Js_undefined.from_opt(wrap),
              justify: Js_undefined.from_opt(justify),
              xl: Js_undefined.from_opt(xl),
              lg: Js_undefined.from_opt(lg),
              md: Js_undefined.from_opt(md),
              sm: Js_undefined.from_opt(sm),
              xs: Js_undefined.from_opt(xs),
              spacing: Js_undefined.from_opt(spacing),
              wrp: Js_undefined.from_opt(wrap)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
