// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact        = require("reason-react/src/reasonReact.js");
var MaterialUi         = require("material-ui");
var Js_undefined       = require("bs-platform/lib/js/js_undefined.js");
var Utils$BsMaterialUi = require("./utils.js");

function make(onClick, dense, disableRipple, disabled, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.IconButton, {
              dense: Utils$BsMaterialUi.unwrapBool(dense),
              disableRipple: Utils$BsMaterialUi.unwrapBool(disableRipple),
              disabled: Utils$BsMaterialUi.unwrapBool(disabled),
              onClick: Js_undefined.from_opt(onClick)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
