// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact        = require("reason-react/src/reasonReact.js");
var MaterialUi         = require("material-ui");
var Js_undefined       = require("bs-platform/lib/js/js_undefined.js");
var Utils$BsMaterialUi = require("./utils.js");

function make(disableUnderline, disabled, error, autoFocus, fullWidth, style, value, onChange, _, className, _type, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.Input, {
              disableUnderline: Utils$BsMaterialUi.unwrapBool(disableUnderline),
              disabled: Utils$BsMaterialUi.unwrapBool(disabled),
              error: Utils$BsMaterialUi.unwrapBool(error),
              fullWidth: Utils$BsMaterialUi.unwrapBool(fullWidth),
              autoFocus: Utils$BsMaterialUi.unwrapBool(autoFocus),
              style: Js_undefined.from_opt(style),
              placeholder: Js_undefined.from_opt(className),
              className: Js_undefined.from_opt(className),
              type: Js_undefined.from_opt(_type),
              value: Js_undefined.from_opt(value),
              onChange: Js_undefined.from_opt(onChange)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
