// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact        = require("reason-react/src/reasonReact.js");
var MaterialUi         = require("material-ui");
var Js_undefined       = require("bs-platform/lib/js/js_undefined.js");
var Utils$BsMaterialUi = require("./utils.js");

function make(className, style, primary, secondary, inset, disableTypography, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.ListItemText, {
              inset: Utils$BsMaterialUi.unwrapBool(inset),
              disableTypography: Utils$BsMaterialUi.unwrapBool(disableTypography),
              style: Js_undefined.from_opt(style),
              className: Js_undefined.from_opt(className),
              primary: Js_undefined.from_opt(primary),
              secondary: Js_undefined.from_opt(secondary)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
