// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact        = require("reason-react/src/reasonReact.js");
var MaterialUi         = require("material-ui");
var Js_undefined       = require("bs-platform/lib/js/js_undefined.js");
var Utils$BsMaterialUi = require("./utils.js");

function make(dense, disablePadding, className, component, style, subheader, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.Paper, {
              dense: Utils$BsMaterialUi.unwrapBool(dense),
              disablePadding: Utils$BsMaterialUi.unwrapBool(disablePadding),
              style: Js_undefined.from_opt(style),
              component: Js_undefined.from_opt(component),
              className: Js_undefined.from_opt(className),
              subheader: Js_undefined.from_opt(subheader)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
