// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact  = require("reason-react/src/reasonReact.js");
var MaterialUi   = require("material-ui");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(className, style, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.ListItemSecondaryAction, {
              style: Js_undefined.from_opt(style),
              className: Js_undefined.from_opt(className)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
