// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact        = require("reason-react/src/reasonReact.js");
var MaterialUi         = require("material-ui");
var Js_undefined       = require("bs-platform/lib/js/js_undefined.js");
var Utils$BsMaterialUi = require("./utils.js");

function make(openMenu, onRequestClose, className, anchorEl, style, value, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.Menu, {
              open: Utils$BsMaterialUi.unwrapBool(openMenu),
              style: Js_undefined.from_opt(style),
              anchorEl: Js_undefined.from_opt(anchorEl),
              className: Js_undefined.from_opt(className),
              value: Js_undefined.from_opt(value),
              onRequestClose: Js_undefined.from_opt(onRequestClose)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
