// Generated by BUCKLESCRIPT VERSION 1.9.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact  = require("reason-react/src/reasonReact.js");
var MaterialUi   = require("material-ui");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(checked, checkedClassName, checkedIcon, disableRipple, disabled, disabledClassName, icon, indeterminate, indeterminateIcon, name, onChange, value, children) {
  return ReasonReact.wrapJsForReason(MaterialUi.Radio, {
              checked: Js_undefined.from_opt(checked),
              checkedClassName: Js_undefined.from_opt(checkedClassName),
              checkedIcon: Js_undefined.from_opt(checkedIcon),
              disableRipple: Js_undefined.from_opt(disableRipple),
              disabled: Js_undefined.from_opt(disabled),
              disabledClassName: Js_undefined.from_opt(disabledClassName),
              icon: Js_undefined.from_opt(icon),
              indeterminate: Js_undefined.from_opt(indeterminate),
              indeterminateIcon: Js_undefined.from_opt(indeterminateIcon),
              name: Js_undefined.from_opt(name),
              onChange: Js_undefined.from_opt(onChange),
              value: Js_undefined.from_opt(value)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
